import type { Metadata } from "next";
import Image from "next/image";
import { Header } from "@/components/header";
import { OtherServices } from "@/components/other-services";
import { TeamSection } from "@/components/team-section";
import { ContactFooter } from "@/components/contact-footer";

export const metadata: Metadata = { title: "Acerca de nosotros", description: "Conoce la historia, principios y profesionales de Smile Dental." };

export default function AcercaPage() {
  return <><Header /><main>
    <section className="page-gutter py-20 lg:py-28"><span className="eyebrow">🏆 Acerca de nosotros</span><h1 className="mt-7 max-w-5xl text-5xl font-semibold leading-[.98] tracking-[-.055em] sm:text-6xl lg:text-7xl">Cuidado dental de primer nivel para sonrisas sanas y radiantes</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-500">Atención excepcional en una clínica moderna, cálida y comprometida con tu bienestar.</p></section>
    <section className="bg-slate-50 py-16"><div className="page-gutter grid grid-cols-2 gap-4 lg:grid-cols-[.7fr_.9fr_.7fr_1.5fr]">{["/images/consulta-dental.jpg","/images/tratamiento-dental.jpg","/images/paciente-feliz.jpg","/images/consulta-dental.jpg"].map((src,i)=><div key={i} className="relative aspect-[4/5] overflow-hidden last:col-span-2 lg:last:col-span-1 lg:last:aspect-auto"><Image src={src} alt="Instalaciones y atención de Smile Dental" fill className="object-cover" sizes="25vw" /></div>)}</div></section>
    <section className="page-gutter py-20 text-center lg:py-28"><h2 className="section-title">Nuestra historia</h2><article className="mx-auto mt-10 max-w-3xl border border-slate-200 p-8 text-left shadow-sm md:p-12"><p className="text-xl font-medium leading-8">Nuestra historia nació de una pasión: transformar vidas mediante una atención dental excepcional.</p><p className="mt-5 leading-7 text-slate-500">Nuestra fundadora, la Dra. María Lubin, imaginó una clínica que combinara odontología avanzada con un trato verdaderamente humano. Desde entonces construimos relaciones duraderas con nuestros pacientes y sus familias.</p><p className="mt-5 leading-7 text-slate-500">Cada visita es una oportunidad para cuidar tu salud, escuchar tus inquietudes y ofrecerte soluciones claras y personalizadas.</p><div className="mt-8 border-t border-slate-200 pt-6 font-semibold text-blue-900">Dra. María Lubin · Fundadora</div></article></section>
    <section className="page-gutter grid items-center gap-10 pb-20 lg:grid-cols-2 lg:pb-28"><div><h2 className="section-title">Principios que definen nuestra identidad</h2>{[["Atención centrada en el paciente","Tu comodidad y satisfacción guían cada decisión."],["Excelencia y experiencia","Buscamos calidad clínica en cada detalle."],["Compasión y empatía","Escuchamos sin apuro y explicamos con claridad."]].map(([t,d])=><div key={t} className="mt-6 border-l-2 border-blue-900 pl-5"><h3 className="font-semibold">{t}</h3><p className="mt-2 text-slate-500">{d}</p></div>)}</div><div className="relative min-h-[560px]"><Image src="/images/doctora.jpg" alt="Doctora de Smile Dental" fill className="object-cover" sizes="50vw" /></div></section>
    <section className="bg-slate-50 py-20 lg:py-28"><div className="page-gutter"><h2 className="section-title max-w-2xl">Juntos impulsamos sonrisas y bienestar</h2><div className="mt-12 grid gap-5 sm:grid-cols-3">{[["230","pacientes atendidos esta semana"],["4","consultorios modernos"],["23+","años de experiencia conjunta"]].map(([n,l],i)=><article key={l} className="border border-slate-200 bg-white p-8"><span className="text-xs font-bold text-red-500">0{i+1}</span><strong className="mt-6 block text-5xl text-red-500">{n}</strong><p className="mt-3 text-slate-500">{l}</p></article>)}</div></div></section>
    <OtherServices /><TeamSection />
  </main><ContactFooter /></>;
}
